DMDirc/DMDirc

- src/com/dmdirc/ChannelFactory.java
- src/com/dmdirc/QueryFactory.java
- src/com/dmdirc/Server.java
- src/com/dmdirc/ServerFactoryImpl.java
- src/com/dmdirc/ServerManager.java
- test/com/dmdirc/ServerTest.java
SM now listens to frame closing events, so Server doesn't need
to hold on to a reference and inform it that it's closing.
> Decouple Server from ServerManager/WindowManager.

- res/com/dmdirc/ui/messages/format.yml
- src/com/dmdirc/ChannelClient.java
- src/com/dmdirc/interfaces/GroupChatUser.java
Use this in the new formatter to avoid having object hashcodes
all over the damn place.
> Add a convenience method to get mode + nickname.

- src/com/dmdirc/DMDircMBassador.java
We rely fairly heavily on events being ordered consistently, seems
like this is the only way to ensure that.
> Make MBassador only use 1 dispatcher/handler.

- src/com/dmdirc/interfaces/ui/ProfilesDialogModel.java
- src/com/dmdirc/ui/core/profiles/CoreProfilesDialogModel.java
- test/com/dmdirc/ui/core/profiles/CoreProfilesDialogModelTest.java
This isn't used in the UI, and doesn't need to exist with the
individual setter methods.
> Remove editProfile method.

- src/com/dmdirc/Server.java
- src/com/dmdirc/interfaces/Connection.java
- src/com/dmdirc/interfaces/GroupChatManager.java
Will remove them from Connection shortly. Then the functionality
can be pulled out of Server into a sane, separate class.
> Copy GroupChat methods into a GroupChatManager.

- src/com/dmdirc/ServerEventHandler.java
Since changing to events we need to fire when changing from
unknown->away. Before, this was handled by the Server being
told about the new message (and then firing listeners).
Fixes #391.
> Fix away state dodgyness.

- src/com/dmdirc/MessageTarget.java
- src/com/dmdirc/Query.java
- src/com/dmdirc/commandparser/commands/chat/Me.java
- src/com/dmdirc/commandparser/commands/context/ChatCommandContext.java
- src/com/dmdirc/commandparser/parsers/ChatCommandParser.java
- src/com/dmdirc/interfaces/Chat.java
- src/com/dmdirc/interfaces/GroupChat.java
- test/com/dmdirc/commandparser/commands/chat/MeTest.java
Doesn't make sense to have this any more, as Chat provides the
common interface between queries + channels.
> Remove references to MessageTarget.

- analysis.gradle
- build.gradle
- fatjar.gradle
- jar.gradle
- publishing.gradle
Makes it a bit less messy, and easier to find the right bits.
> Split up client build file.

- src/com/dmdirc/ui/messages/HighlightManager.java
- test/com/dmdirc/ui/messages/HighlightManagerTest.java
Alternative highlights were never added because the maps were
optimised away; then the list occasionally ended up with null
entries as they were added concurrently.
> Add test for HighlightManager, fix issues.

- src/com/dmdirc/plugins/PluginMetaData.java
- src/com/dmdirc/plugins/implementations/PluginFilesHelper.java
- test/com/dmdirc/ui/messages/HighlightManagerTest.java
This is horribly icky and wrong. The only place it's used is
PluginFilesHelper, which can easily be given its own manager.
Also fix annoying shaded import.
> Remove PluginMetaData.getManager().

- src/com/dmdirc/ui/IconManager.java
I'm planning on removing scoped IconManagers - it's a lot of effort
to maintain them and pass them in everywhere (instead of injecting
them) for almost no gain. I don't think we've ever set a per-server
or per-channel icon, and I can't imagine why we'd want to.
> Make the IconManager injectable using a global config.

- build.gradle
This doesn't seem to actually mark them as generated, but they're
marked as source/test dirs which stops the annoying errors every
time you sync.
> Add hints to tell idea where generated sources are

- src/com/dmdirc/Server.java
- src/com/dmdirc/interfaces/Connection.java
This should probably be moved to the LocalClient interface when 
it exists.
> Add a getNickname to Connection.

- src/com/dmdirc/logger/ProgramErrorManager.java
- src/com/dmdirc/logger/SentryLoggingErrorManager.java
- src/com/dmdirc/ui/core/errors/CoreErrorsDialogModel.java
> Tidy up some error handling.

- build.gradle
No major changes, just a version bump for the Sentry protocol
(for Sentry 7) and removal of UDP connections which we never
used.
> Bump raven to 6.0.0.

- src/com/dmdirc/ui/core/errors/CoreErrorsDialogModel.java
- src/com/dmdirc/ui/core/errors/DisplayableError.java
DisplayableError is now mutable and not an autovalue.
CoreErrorsDialog now stores errors and updates them appropriately.
> Fix broke core errors dialog model.

- src/com/dmdirc/ui/messages/Styliser.java
Add more verbose messages.
Issue DMDirc/Plugins#47
I don't think this fixes the original issue - it fixes
the more-easily-reproducable bug I introduced with the
last commit for this issue. Oops.
Can't reproduce the original now, but if it happens
again the error message should be useful.
> Fix precondition check.

- src/com/dmdirc/FrameContainer.java
- src/com/dmdirc/interfaces/WindowModel.java
Think we're going to stop supporting this. If there's a decent
case for it then it should be done as a DisplayProperty instead.
> Fix NPE when trying to add timestampless lines.

- src/com/dmdirc/Query.java
- src/com/dmdirc/interfaces/PrivateChat.java
Only one place in the core needs the silly IRC format, so just
inline it there.
> Remove Query.getHost.

- src/com/dmdirc/MessageEncoder.java
- src/com/dmdirc/commandparser/commands/server/AllChannels.java
- src/com/dmdirc/events/ChannelDisplayableEvent.java
- src/com/dmdirc/interfaces/Chat.java
Start to move FrameContainers behind an iface so they can be
pulled out.
For now, just cast back when needed.
> Make Chat return a WindowModel.

- src/com/dmdirc/Channel.java
- src/com/dmdirc/ChannelFactory.java
- src/com/dmdirc/FrameContainer.java
- src/com/dmdirc/GlobalWindow.java
- src/com/dmdirc/Query.java
- src/com/dmdirc/QueryFactory.java
- src/com/dmdirc/Server.java
- src/com/dmdirc/ServerFactoryImpl.java
- src/com/dmdirc/ServerManager.java
- src/com/dmdirc/commandparser/parsers/ChannelCommandParser.java
- src/com/dmdirc/commandparser/parsers/ChatCommandParser.java
- src/com/dmdirc/commandparser/parsers/CommandParser.java
- src/com/dmdirc/commandparser/parsers/GlobalCommandParser.java
- src/com/dmdirc/commandparser/parsers/QueryCommandParser.java
- src/com/dmdirc/commandparser/parsers/ServerCommandParser.java
- test/com/dmdirc/ServerManagerTest.java
- test/com/dmdirc/harness/TestCommandParser.java
- test/com/dmdirc/harness/TestWritableFrameContainer.java
Instead of passing them in to the FrameContainer ctor, create
them afterwards.
This means the reference in FrameContainer can't be final but
removes the horrible setOwner() kludge that was previously in
CommandParser, and cuts down the deps needed to pass in to the
FrameContainer ctor.
> Tidy how CommandParsers are created.

- res/com/dmdirc/ui/messages/format.yml
- src/com/dmdirc/ChannelEventHandler.java
- src/com/dmdirc/ServerEventHandler.java
- src/com/dmdirc/events/ChannelListModesRetrievedEvent.java
Stop ChannelListModesRetrieved being displayable - not sure
why it ever was, we don't have a formatter for it.
> Make a couple more events use new formatter.

- src/com/dmdirc/DMDircMBassador.java
This keeps happening, and I don't know why we try to unwrap twice.
Probably only makes sense for certain exception types...
> Fix NPE on event bus errors.

- src/com/dmdirc/Query.java
For some reason we're checking hostname (e.g. dmdirc.com)
against full hosts (e.g. chris!ident@dmdirc.com) and expecting
them to match.
Queries now check on nicknames.
> Fix some query nonsense.

- gradle/jar.gradle
This allows service entries to be included.
> Relax META-INF exclusions for jars.

- src/com/dmdirc/commandparser/parsers/CommandParser.java
- src/com/dmdirc/ui/input/InputHandler.java
Stop the InputHandler running off to the global command manager for
commands - instead get them from the command parser it's associated
with.
Fixes #47
> Only validate/wrap commands that exist locally.

- src/com/dmdirc/config/ConfigFileBackedConfigProvider.java
- test/com/dmdirc/config/ConfigFileBackedConfigProviderTest.java
The "old" profiles were pre 0.6.3m1 - if anyone upgrades from that
long ago they'll just lose their profiles.
> Remove profile migration logic.

- src/com/dmdirc/Query.java
We don't need to reregister on nick change now, as we get all
the events anyway and filter them manually.
> Remove CallbackNotFoundException, tidy up Query.

- test/com/dmdirc/commandparser/aliases/ActionAliasMigratorTest.java
- test/com/dmdirc/commandparser/aliases/DefaultAliasInstallerTest.java
- test/com/dmdirc/commandparser/auto/YamlAutoCommandStoreTest.java
- test/com/dmdirc/config/ConfigFileBackedConfigProviderTest.java
- test/com/dmdirc/config/IdentityManagerTest.java
- test/com/dmdirc/logger/DiskLoggingErrorManagerTest.java
- test/com/dmdirc/tests/JimFsRule.java
- test/com/dmdirc/util/URLBuilderTest.java
This means each test doesn't have to set it up and tear it down
manually (although only one actually did bother to tear it down :)).
> Add a JUnit rule for using JimFS.

- test/com/dmdirc/commandparser/aliases/ActionAliasMigratorTest.java
- test/com/dmdirc/commandparser/aliases/DefaultAliasInstallerTest.java
- test/com/dmdirc/commandparser/auto/YamlAutoCommandStoreTest.java
- test/com/dmdirc/config/ConfigFileBackedConfigProviderTest.java
- test/com/dmdirc/config/IdentityManagerTest.java
- test/com/dmdirc/logger/DiskLoggingErrorManagerTest.java
- test/com/dmdirc/tests/JimFsRule.java
- test/com/dmdirc/util/URLBuilderTest.java
This saves getting the FS and suffering the barrage of warnings
related to auto-closeable resources.
> Add getPath utility method to JimFsRule.

- src/com/dmdirc/ServerEventHandler.java
We were raising notices as all coming from the local user, not
the person that sent the notice. This is... unideal.
> Fix source of notice events.

- src/com/dmdirc/commandline/CommandLineOptionsModule.java
- src/com/dmdirc/commandparser/commands/CommandModule.java
- src/com/dmdirc/ui/messages/sink/MessagesModule.java
Dagger 2.0 appears to require each method in a module to have a
unique name. In some cases we've used overloads with the same name.
Also, remove a bunch of boilerplate javadoc.
Issue #601
> Ensure module methods have unique names.

- src/com/dmdirc/config/ConfigBinder.java
- src/com/dmdirc/config/ConfigValueRetriever.java
- test/com/dmdirc/config/ConfigValueRetrieverTest.java
The logic to get a correctly typed setting given a class is
pretty general purpose, and will be useful elsewhere. Pull
it out of ConfigBinder and add some tests for it.
> Extract config value retrieving from binder.

- src/com/dmdirc/ui/messages/EventFormat.java
- src/com/dmdirc/ui/messages/EventFormatter.java
- src/com/dmdirc/ui/messages/YamlEventFormatProvider.java
- test/com/dmdirc/ui/messages/EventFormatterTest.java
This allows formats that may be multi-line (whois results,
probably MOTD results at some point, etc...) to show a header
and footer around the actual content.
> Add formatter support for before/after templates.

- src/com/dmdirc/ui/messages/MultiEventFormatProvider.java
- test/com/dmdirc/ui/messages/MultiEventFormatProviderTest.java
This will allow plugins to supply their own format providers
while still allowing the user to override them using the
main format.yml file.
Issue #622
> Add format provider that handles multiple sources.

- build.gradle
- src/com/dmdirc/logger/SentryErrorReporter.java
This enables release tracking in sentry.
> Use snapshot version of raven, send relase.

- src/com/dmdirc/events/DisplayProperty.java
- src/com/dmdirc/events/DisplayPropertyMap.java
- src/com/dmdirc/ui/messages/EventFormat.java
- src/com/dmdirc/ui/messages/EventFormatter.java
- src/com/dmdirc/ui/messages/Line.java
- src/com/dmdirc/ui/messages/YamlEventFormatProvider.java
- test/com/dmdirc/ui/messages/EventFormatterTest.java
Formats defined in YAML can specify 'timestamps: false' to hide
the default timestamp for lines associated with that event.
Closes #633
> Add display property to suppress timestamps.

- src/com/dmdirc/ui/WindowManager.java
- test/com/dmdirc/ui/WindowManagerTest.java
Despite its name and description, the WindowManager relied on
each FrameContainer having a reference to its parents and all
its children.
The WindowManager now stores this information itself, and so
the FrameContainer methods can be gradually phased out.
> Make the WindowManager track windows.

- src/com/dmdirc/FrameContainer.java
- src/com/dmdirc/interfaces/InputModel.java
- src/com/dmdirc/interfaces/WindowModel.java
Instead of WindowModel defining lots of methods on the off-chance
that the window is writable, pull them all into a separate
optional InputModel.
For ease of transition, FrameContainer will just implement both,
but eventually the input handling should be pulled out into
its own class.
> Introduce a model for window input.

- src/com/dmdirc/FrameContainer.java
- src/com/dmdirc/interfaces/WindowModel.java
- src/com/dmdirc/ui/WindowManager.java
- test/com/dmdirc/ui/WindowManagerTest.java
This allows windows to be uniquely identified and shared with
clients that are running outside of the DMDirc process (e.g.
a web UI, or a remote instance).
> Assign IDs to windows.

- src/com/dmdirc/events/BaseDisplayableEvent.java
- src/com/dmdirc/events/ChannelDisplayableEvent.java
- src/com/dmdirc/events/DisplayableEvent.java
- src/com/dmdirc/events/QueryDisplayableEvent.java
- src/com/dmdirc/events/ServerDisplayableEvent.java
- src/com/dmdirc/events/UnknownCommandEvent.java
- src/com/dmdirc/util/EventUtils.java
Now everything is using events, we don't need the legacy
format identifier.
> Remove unused DisplayableEvent properties.

- src/com/dmdirc/Server.java
- src/com/dmdirc/ServerManager.java
- src/com/dmdirc/events/DisplayableEvent.java
- src/com/dmdirc/events/FrameEvent.java
- src/com/dmdirc/events/SourcedEvent.java
- src/com/dmdirc/ui/WindowManager.java
- src/com/dmdirc/ui/input/InputHandler.java
For #662, it makes sense to have a standard way to
get the source from events we may wish to filter.
This introduces a SourcedEvent interface, and adapts classes
to use it.
> Add a base class for events with a WindowModel source.

- src/com/dmdirc/GroupChatManagerImpl.java
- src/com/dmdirc/Server.java
- src/com/dmdirc/ui/messages/HighlightManager.java
- test/com/dmdirc/ui/messages/HighlightManagerTest.java
In preparation for child eventbusses being removed, anything
trying to subscribe to specific windows now needs an explicit
check.
Issue #662
> Add source checks for eventbus handlers.

- src/com/dmdirc/tls/KeyStoreLocator.java
This provides a nice interface to find a system-wide keystore
for us to use for trusted certificates.
Issue #664
> Add a KeyStoreLocator.

- src/com/dmdirc/Server.java
- src/com/dmdirc/interfaces/Connection.java
Guava provides a nice class which uses the public suffix list,
so we can ditch all of our hand-crafted logic and pathetically
small list of top level domains and do it properly.
> Simplify how we determine network names.

- src/com/dmdirc/ChannelMap.java
If a channel is parted for any reason other than a disconnect
(e.g. a local /part, or a remote part/kick) then the channel
shouldn't be rejoined on reconnection.
Closes #667
> Only rejoin channels that active when disconnected

- res/com/dmdirc/ui/messages/format.yml
- src/com/dmdirc/Server.java
- src/com/dmdirc/events/ChannelHighlightEvent.java
- src/com/dmdirc/events/QueryHighlightEvent.java
- src/com/dmdirc/ui/messages/HighlightManager.java
- src/com/dmdirc/ui/messages/UnreadStatusManager.java
- test/com/dmdirc/ui/messages/HighlightManagerTest.java
Instead of wrapping the source event and modifying it, they are
now proper events that are displayed themselves (and the original
message is suppressed).
This allows highlights to be formatted differently.
Issue #669
> Change highlights into proper displayable events.

- res/com/dmdirc/config/defaults/default/defaults
- res/com/dmdirc/ui/messages/format.yml
- src/com/dmdirc/ui/messages/HighlightManager.java
- src/com/dmdirc/ui/messages/YamlEventFormatProvider.java
- test/com/dmdirc/ui/messages/HighlightManagerTest.java
Allow colours in formats to be hex. Closes #631.
Fix ordering of highlighted messages. #669.
> Specify background colour for highlight events.

- src/com/dmdirc/ui/messages/UnreadStatusManager.java
Events aren't unread and shouldn't affect the display colour of
a window if they're hidden.
> Fix counting of events.

- src/main/java/com/dmdirc/Query.java
- src/main/java/com/dmdirc/Server.java
- src/main/java/com/dmdirc/ServerEventHandler.java
- src/main/java/com/dmdirc/interfaces/Connection.java
It doesn't make sense to have a public method in Connection to
muddle around with how queries are tracked, nor for queries to
tell servers when they change (creating a dependency loop).
Instead, have the ServerEventHandler tell Server.
> Tidy up nick change handling.

- src/main/java/com/dmdirc/util/LogUtils.java
NoClassDefFoundError only takes a message (no source). Try
throwable-only and message-only ctors in addition to the
two-arg ctors.
> Make LogUtils try some more ctors.

- src/main/java/com/dmdirc/events/FrameOpenedEvent.java
- src/main/java/com/dmdirc/ui/WindowManager.java
For some reason this was only exposed through the WindowManager
listeners.
> Add an event for frame opened.

- src/main/java/com/dmdirc/Server.java
If the user doesn't specify a port, allow the parser implementation
to figure it out for itself. This allows for things like SRV lookups,
or different default ports per protocol.
> Don't fiddle with ports before passing them to the parser.

- src/main/resources/com/dmdirc/version.config
This allows running DMDirc from IDEA, which seems useful.
Running a normal build just replaces the file in the build output.
> Add dummy version.config.

- api/src/main/java/com/dmdirc/config/AddonConfig.java
- api/src/main/java/com/dmdirc/config/GlobalConfig.java
- api/src/main/java/com/dmdirc/config/UserConfig.java
- src/main/java/com/dmdirc/ClientModule.java
- src/main/java/com/dmdirc/config/ConfigModule.java
At present anything requesting the global config has to depend on
ClientModule, which won't necessarily be exposed through the API.
Move @GlobalConfig, @AddonConfig and @UserConfig to top level
classes in API, and provide both versions of them for now.
> Add config annotations to API.

- src/main/java/com/dmdirc/Channel.java
- src/main/java/com/dmdirc/ui/messages/IRCLine.java
- src/main/java/com/dmdirc/ui/messages/StyledMessageUtils.java
- src/main/java/com/dmdirc/ui/messages/Styliser.java
- src/test/java/com/dmdirc/ui/messages/StyledMessageUtilsTest.java
- src/test/java/com/dmdirc/ui/messages/StyliserIndicesTest.java
- src/test/java/com/dmdirc/ui/messages/StyliserTest.java
The styliser needs an interface extracting into the API, and
we don't really want huge static methods defined on that.
> Move static styliser methods to new class.

- src/main/java/com/dmdirc/ui/input/TabCompletionMatches.java
Make it extend a list instead of wrapping it, so we can just replace
all usages with... an actual list.
> Deprecate TabCompletionMatches.

- api/src/main/java/com/dmdirc/events/DisplayableEvent.java
- api/src/main/java/com/dmdirc/interfaces/Displayable.java
- api/src/main/java/com/dmdirc/interfaces/GroupChatUser.java
This will allow the formatter to check if strings coming from
(for example) users in channels should be formatted specially,
such as by colouring or linking them.
Issues #424 and DMDirc/Plugins#507
> Add base interface for objects with display properties.

- src/main/java/com/dmdirc/ui/messages/EventFormatter.java
- src/main/java/com/dmdirc/ui/messages/EventPropertyManager.java
- src/main/java/com/dmdirc/ui/messages/Styliser.java
If an object in a formatter tag ({{foo.bar.baz}}) is Displayable,
then we will modify the output based on its display properties.
Currently only supports user links and foreground colours.
This also changes the internal format of nickname links to be
`\u16<nick to link to>\u16<text to show>\u16`, allowing the
link and text to differ. This means if you formatted users
by showing their realname, you could still click them to
open a query.
Closes #424
Closes DMDirc/Plugins#507
> Apply object display properties when formatting events.

- src/main/java/com/dmdirc/ui/messages/Styliser.java
We now specify the default colour using display properties, not
by ascribing special value to the first colour code in a message.
Closes #741
> Remove legacy default colour behaviour.

- src/main/java/com/dmdirc/ui/messages/EventFormatter.java
This allows "unstyled" to actually work.
Closes #755
> Apply display properties to a value before running functions on it.

- api/src/main/java/com/dmdirc/events/DisplayLocation.java
- api/src/main/java/com/dmdirc/events/DisplayProperty.java
- src/main/java/com/dmdirc/plugins/PluginEventFormatManager.java
- src/main/java/com/dmdirc/ui/messages/BackBufferImpl.java
- src/main/java/com/dmdirc/ui/messages/DisplayLocationManager.java
- src/main/java/com/dmdirc/ui/messages/EventFormatter.java
- src/main/java/com/dmdirc/ui/messages/YamlEventFormatProvider.java
I'm sure this will be changed/redone, but this is at least a start by allowing
certain events to go to all windows (eg ServerNotices)
Ideally it would be possible for some events to only be displayed in the window
that generated them (eg if I do /notice foo bar the ">-{{target}}-> {{message}}"
message only appears in the window I ran the command in, not either just the
server window or all the windows, but this would need changes to a bunch of
events to make them include a source window.
> Allow specifying a window for DisplayableEvents in format.yml (Issue #459)

- src/main/java/com/dmdirc/ChannelEventHandler.java
> Publish channel events using publish() not publishAsync() to ensure correct ordering.

- src/main/java/com/dmdirc/util/URIParser.java
- src/test/java/com/dmdirc/util/URIParserURIParameterizedTest.java
Because of the weird string->URI parts->URI conversion we do,
we have to manually decode special entities when converting
them into URI parts. (Otherwise the URI constructor encodes
them a second time)
> Fix handling of special chars in passwords when using /newserver.

- build.gradle
- src/main/java/com/dmdirc/ui/messages/UnreadStatusManagerImpl.java
Reduces unread status changes to publish to the eventbus
at most once every 200ms per window. These events are
handled synchronously on the EDT so cause massive
performance issues.
When connecting to several bouncers with huge backbuffers
this makes the client usable in seconds rather than tens of minutes.
Internally this uses RX to handle the throttling, because it's
super easy. We might eventually want to expose that externally
instead of using an event bus, but I'm not sure.
> Throttle unread status changes.
