DMDirc/DMDirc

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/Channel.java
src/com/dmdirc/ChannelEventHandler.java
src/com/dmdirc/ui/messages/BackBuffer.java

This permanently enables th new event-based formatter,
and disables the old doNotification path for the events
that it covers.

Go go gadget new event formatter.

---

src/com/dmdirc/config/prefs/PreferencesCategory.java
src/com/dmdirc/config/prefs/PreferencesDialogModel.java
test/com/dmdirc/config/prefs/PreferencesDialogModelTest.java

This things actually have a change to add themselves to
the prefs dialog.

Synchronously trigger ClientPrefsOpenedEvent.

---

res/com/dmdirc/config/defaults/default/defaults
src/com/dmdirc/Server.java
src/com/dmdirc/ui/messages/HighlightManager.java

Make highlight colours configurable.

---

src/com/dmdirc/config/profiles/Profile.java
src/com/dmdirc/config/profiles/YamlProfileStore.java
src/com/dmdirc/ui/core/profiles/CoreProfilesDialogModel.java
src/com/dmdirc/ui/core/profiles/MutableProfile.java

These are highlight strings other than the current nickname that
the user wishes to highlight on (e.g. their real name, or 'D*').

Add highlight strings to profiles.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/ChannelEventHandler.java
src/com/dmdirc/Query.java
src/com/dmdirc/ServerEventHandler.java
src/com/dmdirc/events/ChannelGotNamesEvent.java
src/com/dmdirc/events/ChannelGotTopicEvent.java
src/com/dmdirc/events/ChannelListModesRetrievedEvent.java
src/com/dmdirc/events/ChannelModeChangeEvent.java
src/com/dmdirc/events/ChannelModesDiscoveredEvent.java
src/com/dmdirc/events/ChannelNickChangeEvent.java
src/com/dmdirc/events/ChannelNoTopicEvent.java
src/com/dmdirc/events/ChannelSelfModeChangeEvent.java
src/com/dmdirc/events/ChannelUserModeChangeEvent.java
src/com/dmdirc/events/QueryNickChangeEvent.java
src/com/dmdirc/events/ServerAuthNoticeEvent.java
src/com/dmdirc/events/ServerCtcpReplyEvent.java
src/com/dmdirc/events/ServerGotPingEvent.java
src/com/dmdirc/events/ServerMotdEndEvent.java
src/com/dmdirc/events/ServerMotdLineEvent.java
src/com/dmdirc/events/ServerMotdStartEvent.java
src/com/dmdirc/events/ServerNickChangeEvent.java
src/com/dmdirc/events/ServerNoPingEvent.java
src/com/dmdirc/events/ServerPingSentEvent.java
src/com/dmdirc/events/ServerServerNoticeEvent.java
src/com/dmdirc/events/ServerUnknownActionEvent.java
src/com/dmdirc/events/ServerUnknownMessageEvent.java
src/com/dmdirc/events/ServerUnknownNoticeEvent.java
src/com/dmdirc/events/ServerUserModesEvent.java
src/com/dmdirc/events/ServerWalldesyncEvent.java
src/com/dmdirc/ui/messages/HighlightManager.java

We no longer need to be consistent with the odd casing/naming
of actions.

Fix naming of events.

---

src/com/dmdirc/ui/messages/Styliser.java

Fix tooltips showing up everywhere.

---

src/com/dmdirc/interfaces/ui/ProfilesDialogModel.java
src/com/dmdirc/interfaces/ui/ProfilesDialogModelListener.java
src/com/dmdirc/ui/core/profiles/CoreProfilesDialogModel.java
src/com/dmdirc/ui/core/profiles/EditSelectedHighlightValidator.java
src/com/dmdirc/ui/core/profiles/ProfilesDialogModelAdapter.java

Add highlights to CoreProfilesDialogModel.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/ui/messages/EventPropertyManager.java

Group them by function so the file is a bit easier to navigate.
Use nice syntax for multi-line topic format.
Also add function to do bracketed crazyness for events with reasons.

Tidy up formats a bit.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/Channel.java
src/com/dmdirc/ChannelEventHandler.java
src/com/dmdirc/events/ChannelSelfJoinEvent.java
src/com/dmdirc/ui/messages/EventPropertyManager.java

This, uh, breaks some channels a little. Will fix in a follow-up.
Add support for Optionals in the event property manager.

Use new formatter for channel joins.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/CustomWindow.java
src/com/dmdirc/FrameContainer.java
src/com/dmdirc/GlobalWindow.java
src/com/dmdirc/Query.java
src/com/dmdirc/Server.java

We now need it to exist independently of anything requesting it,
otherwise we miss lines being added.

Stop BackBuffer being so lazy.

---

src/com/dmdirc/MessageEncoder.java
src/com/dmdirc/ServerManager.java
src/com/dmdirc/commandparser/CommandManager.java
src/com/dmdirc/commandparser/commands/server/AllChannels.java
src/com/dmdirc/commandparser/commands/server/JoinChannelCommand.java
src/com/dmdirc/commandparser/commands/server/Message.java
src/com/dmdirc/commandparser/parsers/CommandParser.java
src/com/dmdirc/interfaces/Connection.java
src/com/dmdirc/lists/GroupListManager.java
src/com/dmdirc/ui/messages/Styliser.java
src/com/dmdirc/ui/messages/sink/ChannelMessageSink.java
src/com/dmdirc/ui/messages/sink/CommonChannelsMessageSink.java
test/com/dmdirc/ServerManagerTest.java
test/com/dmdirc/commandparser/parsers/CommandParserTest.java
test/com/dmdirc/ui/messages/IntelligentLinkingTest.java

Remove them from the Connection interface.

Use new GroupChatManager methods.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/GroupChatManagerImpl.java
src/com/dmdirc/GroupChatManagerImplFactory.java
src/com/dmdirc/Server.java
src/com/dmdirc/ServerEventHandler.java
src/com/dmdirc/ServerFactoryImpl.java
src/com/dmdirc/interfaces/Connection.java
test/com/dmdirc/ServerEventHandlerTest.java
test/com/dmdirc/ServerTest.java

For now this is just a straight(ish) copy of the way Server worked.
Need to make it use events in the future which should simplify it
quite a bit.

Make a separate GroupChatManager.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/Query.java

Removes some usages of server.parseHostMask which needs to die.

Use new formatter for query action/msg.

---

src/com/dmdirc/ui/messages/YamlEventFormatProvider.java

If we can't display any lines, there's not much point carrying on.

Make formatter load failures a fatal error.

---

src/com/dmdirc/commandparser/commands/channel/Cycle.java
src/com/dmdirc/commandparser/commands/channel/Names.java
src/com/dmdirc/commandparser/commands/channel/Part.java
test/com/dmdirc/commandparser/commands/channel/NamesTest.java
test/com/dmdirc/commandparser/commands/channel/PartTest.java

Most use logic we don't wrap yet :-/

Replace Channel with GroupChat in a few commands.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/GroupChatManagerImpl.java

Nicer than having Channel poke it explicitly.

Make GroupChatManager listen for channel closing.

---

src/com/dmdirc/logger/ErrorManager.java
src/com/dmdirc/logger/ProgramErrorErrorManager.java
src/com/dmdirc/logger/ProgramErrorFactory.java
src/com/dmdirc/logger/ProgramErrorManager.java

- Add a ProgramErrorFactory
- Add a ProgramErrorErrorManager (I'm awful at names...)

Some more work on errors.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/GroupChatManagerImpl.java
src/com/dmdirc/Invite.java
src/com/dmdirc/ServerEventHandler.java
src/com/dmdirc/interfaces/Connection.java
test/com/dmdirc/InviteTest.java

Delete the duplicated methods from Connection.

Use new InviteManager iface.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/ChannelFactory.java
src/com/dmdirc/CustomWindow.java
src/com/dmdirc/FrameContainer.java
src/com/dmdirc/GlobalWindow.java
src/com/dmdirc/Query.java
src/com/dmdirc/QueryFactory.java
src/com/dmdirc/Server.java
src/com/dmdirc/ServerFactoryImpl.java
src/com/dmdirc/commandparser/commands/global/OpenWindow.java
src/com/dmdirc/ui/messages/sink/CustomWindowMessageSink.java
test/com/dmdirc/WritableFrameContainerTest.java
test/com/dmdirc/harness/TestWritableFrameContainer.java

Remove urlBuilder params.

---

src/com/dmdirc/plugins/PluginInfo.java

Split giant methods up, simplify logic in a few places.

Tidy up PluginInfo a bit.

---

src/com/dmdirc/Channel.java

Publish nicklist clear events synchronously.

---

src/com/dmdirc/ClientModule.java
src/com/dmdirc/logger/SentryLoggingErrorManager.java
src/com/dmdirc/util/LoggingExecutorService.java

Add a LoggingExecutorService and use it for sentry error reporting.

---

src/com/dmdirc/config/ConfigBinder.java
src/com/dmdirc/config/ConfigBinding.java
src/com/dmdirc/ui/messages/HighlightManager.java
test/com/dmdirc/config/ConfigBinderTest.java

Fix HighlightManager not respecting optionals.

---

src/com/dmdirc/commandparser/commands/server/OpenQuery.java

Make query online only.

---

src/com/dmdirc/ui/core/profiles/CoreProfilesDialogModel.java

Add not empty validators for add/edit nicknames.

---

src/com/dmdirc/interfaces/ui/ProfilesDialogModel.java
src/com/dmdirc/ui/core/profiles/CoreProfilesDialogModel.java
test/com/dmdirc/ui/core/profiles/CoreProfilesDialogModelTest.java

Probably Fixes DMDirc/Plugins#327 and Fixes #491 if not the traces
will be completely different.

Tidy up CoreProfilesDialogModel and bit.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/interfaces/GroupChat.java

These are just proxies to ChannelInfo for now.

Add some mode methods to GroupChat.

---

src/com/dmdirc/commandparser/commands/server/JoinChannelCommand.java

Synchronise access to maplist.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/commandparser/commands/channel/Ban.java
src/com/dmdirc/commandparser/commands/channel/Cycle.java
src/com/dmdirc/commandparser/commands/channel/Invite.java
src/com/dmdirc/commandparser/commands/channel/KickReason.java
src/com/dmdirc/commandparser/commands/channel/Mode.java
src/com/dmdirc/commandparser/commands/channel/Names.java
src/com/dmdirc/commandparser/commands/channel/Part.java
src/com/dmdirc/commandparser/commands/channel/SetNickColour.java
src/com/dmdirc/commandparser/commands/channel/ShowTopic.java
src/com/dmdirc/commandparser/commands/context/ChannelCommandContext.java
src/com/dmdirc/commandparser/commands/global/SetCommand.java
src/com/dmdirc/commandparser/parsers/ChannelCommandParser.java
src/com/dmdirc/interfaces/GroupChat.java
test/com/dmdirc/commandparser/commands/channel/BanTest.java
test/com/dmdirc/commandparser/commands/channel/ModeTest.java

(This depends on a plugins change)

Replace Channel with GroupChat in commands.

---

src/com/dmdirc/ChannelMap.java
src/com/dmdirc/GroupChatManagerImpl.java
src/com/dmdirc/GroupChatManagerImplFactory.java
src/com/dmdirc/Server.java

This will go in a plugin instead.

Remove channel who functionality.

---

src/com/dmdirc/config/ConfigManager.java

Fix CME in ConfigManager.removeListeners.

---

src/com/dmdirc/config/ConfigFileBackedConfigProvider.java

This is fairly trivial to implement with streams/lambdas,
no need to have our own hand-rolled list implementation
for it.

Remove use of WeakList.

---

res/com/dmdirc/ui/messages/format.yml

Fix nonsense in the formatter.

---

src/com/dmdirc/commandline/CommandLineParser.java
src/com/dmdirc/ui/core/about/CoreAboutDialogModel.java
src/com/dmdirc/updater/UpdaterModule.java
test/com/dmdirc/ui/core/about/CoreAboutDialogModelTest.java

I also made the launcher version an optional, because
optionals are good.

Add launcher version to the about dialog.

---

README.md

Kick off some basic dev info by documenting the new error handling.

Add a README.

---

src/com/dmdirc/plugins/PluginInfo.java
src/com/dmdirc/plugins/PluginManager.java

We have a path, it doesn't really make sense to take the filename,
then take the directory, then create a new path using those...

Fix weird plugin path construction.

---

src/com/dmdirc/Server.java

Split out error description getting into its own method. Other
minor changes.

Tidying of Server.

---

src/com/dmdirc/FrameContainer.java
src/com/dmdirc/ServerEventHandler.java

I think these will eventually go away entirely, once everything
is event-bus'd, but I'm not entirely sure how that works any
more :(

Tidy up some unused/uncommonly used methods.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/Channel.java
src/com/dmdirc/FrameContainer.java
src/com/dmdirc/Query.java
src/com/dmdirc/Server.java
src/com/dmdirc/ServerEventHandler.java
src/com/dmdirc/events/ServerUnknownProtocolEvent.java
src/com/dmdirc/events/ServerUserModesEvent.java
src/com/dmdirc/interfaces/WindowModel.java

This allows us to remove a fair chunk of the notification
handling functionality in FrameContainer.
Issue #426

Move some more formats over to events.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/events/UserInfoResponseEvent.java
src/com/dmdirc/ui/messages/EventFormat.java
src/com/dmdirc/ui/messages/EventFormatter.java
src/com/dmdirc/ui/messages/YamlEventFormatProvider.java
test/com/dmdirc/ui/messages/EventFormatterTest.java

This allows events to iterate over a collection property, and
adds formatting for whois results. It needs a lot of tidying,
but it's a start...

Add ugly event-based whois output.

---

build.gradle
src/com/dmdirc/DMDircMBassador.java

This release contains some performance improvements compared
to the version we were using.
Error handlers are now passed in at construction time, so
there was a small bit of refactoring required.

Update to MBassador 1.2.4.

---

src/com/dmdirc/ui/messages/UiMessagesModule.java

Use the new MutliEventFormatProvider.

---

src/com/dmdirc/plugins/PluginEventFormatManager.java
src/com/dmdirc/plugins/PluginModule.java

Allow plugins to specify event formats.

---

src/com/dmdirc/DMDircMBassador.java
src/com/dmdirc/util/LogUtils.java

Also make event bus errors have a better message.
Closes #627

Make LogUtils more robust.

---

src/com/dmdirc/commandparser/commands/channel/ShowTopic.java

Use events in ShowTopic command.

---

src/com/dmdirc/FrameContainer.java
src/com/dmdirc/commandparser/commands/Command.java
src/com/dmdirc/interfaces/WindowModel.java

Remove ramaining addLine methods.

---

src/com/dmdirc/CustomWindow.java
src/com/dmdirc/commandparser/commands/global/Echo.java
src/com/dmdirc/commandparser/commands/server/JoinChannelCommand.java

These will be going away shortly.

Remove usages of FrameContainer window methods.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/FrameContainer.java
src/com/dmdirc/GroupChatManagerImpl.java
src/com/dmdirc/Query.java
src/com/dmdirc/Server.java
src/com/dmdirc/commandparser/CommandManager.java
src/com/dmdirc/commandparser/aliases/AliasCommandHandler.java
src/com/dmdirc/commandparser/auto/AutoCommandHandler.java
src/com/dmdirc/commandparser/commands/global/AllServers.java
src/com/dmdirc/commandparser/commands/global/Help.java
src/com/dmdirc/commandparser/commands/global/Ifplugin.java
src/com/dmdirc/commandparser/commands/server/AllChannels.java
src/com/dmdirc/commandparser/commands/server/Message.java
src/com/dmdirc/commandparser/commands/server/OpenQuery.java
src/com/dmdirc/commandparser/parsers/CommandParser.java
src/com/dmdirc/interfaces/WindowModel.java
src/com/dmdirc/ui/input/InputHandler.java
test/com/dmdirc/commandparser/aliases/AliasCommandHandlerTest.java
test/com/dmdirc/commandparser/auto/AutoCommandHandlerTest.java
test/com/dmdirc/commandparser/parsers/CommandParserTest.java

Migrate all users to using the InputModel.

Remove input methods from WindowModel.

---

src/com/dmdirc/ChannelEventHandler.java
src/com/dmdirc/ServerEventHandler.java

The parser now uses the new API too, so we don't need to
do horrible things to convert.

Update date handling after parser changes.

---

src/com/dmdirc/tls/CertificateManager.java

Use KeyStoreLocator in CertificateManager.

---

src/com/dmdirc/Channel.java
src/com/dmdirc/ChannelMap.java
src/com/dmdirc/interfaces/GroupChat.java

We'll use this to decide whether to auto-rejoin or not.
Issue #677

Track reasons for parting in Channel.

---

res/com/dmdirc/ui/messages/format.yml
src/com/dmdirc/events/ChannelActionHighlightEvent.java
src/com/dmdirc/events/QueryActionHighlightEvent.java
src/com/dmdirc/ui/messages/HighlightManager.java

Add formatting action highlights.

---

test/com/dmdirc/ui/core/about/CoreAboutDialogModelTest.java

This fails reliably for me locally, but seems to pass CI. There's
some non-detminism somewhere, I guess.

Ignore flakey test.

---

build.gradle

Change dependencies after parser group change.

---

src/main/java/com/dmdirc/events/BaseQueryActionEvent.java
src/main/java/com/dmdirc/events/BaseQueryMessageEvent.java
src/main/java/com/dmdirc/events/BaseQueryTextEvent.java
src/main/java/com/dmdirc/events/QueryActionEvent.java
src/main/java/com/dmdirc/events/QueryActionHighlightEvent.java
src/main/java/com/dmdirc/events/QueryDisplayableEvent.java
src/main/java/com/dmdirc/events/QueryEvent.java
src/main/java/com/dmdirc/events/QueryHighlightEvent.java
src/main/java/com/dmdirc/events/QueryMessageEvent.java
src/main/java/com/dmdirc/ui/messages/HighlightManager.java

Use PrivateChat for events, not Query.

---

api/src/main/java/com/dmdirc/events/DisplayProperty.java
src/main/java/com/dmdirc/ChannelClient.java

Add a display property for linking to users.

---

src/main/java/com/dmdirc/ui/messages/StyledMessageUtils.java
src/test/java/com/dmdirc/ui/messages/StyledMessageUtilsTest.java

Fix stripping nickname control codes.

---

src/main/resources/com/dmdirc/config/defaults/default/defaults

showrawwindow isn't a setting.

---

src/main/java/com/dmdirc/ui/messages/StyledMessageUtils.java
src/test/java/com/dmdirc/ui/messages/StyliserIndicesTest.java

Fix getStyledText() scrubbing underline and stop chars.

---

build.gradle
gradle/jar.gradle
src/main/java/com/dmdirc/ClientActivator.java

This won't affect normal use of the client, other than it having
a few extra unused classes and some additional lines in the
manifest.
Issue #750

Add OSGI dependency, activator.

---

src/main/java/com/dmdirc/ui/messages/EventPropertyManager.java
src/test/java/com/dmdirc/ui/messages/EventPropertyManagerTest.java

Add "unstyled" formatter func to strip control codes.

---

build.gradle
bundles/com.dmdirc.util.io.yaml/build.gradle
bundles/com.dmdirc.util.io.yaml/src/main/java/com/dmdirc/util/io/yaml/BaseYamlStore.java
bundles/com.dmdirc.util.io.yaml/src/main/java/com/dmdirc/util/io/yaml/YamlReaderUtils.java
settings.gradle
src/main/java/com/dmdirc/commandparser/aliases/YamlAliasStore.java
src/main/java/com/dmdirc/commandparser/auto/YamlAutoCommandStore.java
src/main/java/com/dmdirc/config/prefs/reader/CategoryReader.java
src/main/java/com/dmdirc/config/prefs/reader/PreferencesReader.java
src/main/java/com/dmdirc/config/profiles/YamlProfileStore.java
src/main/java/com/dmdirc/ui/messages/YamlEventFormatProvider.java

Move Yaml utils to com.dmdirc.util.io.yaml bundle.

---

src/main/java/com/dmdirc/commandparser/commands/CommandModule.java
src/main/java/com/dmdirc/commandparser/commands/global/ReloadFormat.java
src/main/java/com/dmdirc/ui/messages/EventFormatProvider.java
src/main/java/com/dmdirc/ui/messages/MultiEventFormatProvider.java
src/main/java/com/dmdirc/ui/messages/YamlEventFormatProvider.java

Add /reloadformat command.

---

src/main/java/com/dmdirc/GroupChatManagerImpl.java
src/main/java/com/dmdirc/Server.java

- GroupChatManager never subscribed to the event bus
- Comparing Optional<Connection> to Connection fails
Closes #782

Fix a couple of issues with closing channels.

---

api/build.gradle
build.gradle

Update autovalue to 1.6.
